on:
  - push

name: "CI"

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    
    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: yarn install --frozen-lockfile
    - run: yarn run lint
    - run: |
        pwd
        ls -lah node_modules/@nomad-ts
        ls -lah node_modules/@nomad-ts/core
        ls -lah node_modules/@nomad-ts/core/lib
        cat node_modules/@nomad-ts/core/package.json
    - run: yarn run build
    - run: yarn run test
